-- 1. Crear tabla Locations
create table public.locations (
  id bigint generated by default as identity primary key,
  name text not null,
  user_id uuid references public.profiles(id) not null,
  created_at timestamp with time zone default now()
);

-- 2. Agregar FK a inventory_items
alter table public.inventory_items 
add column location_id bigint references public.locations(id);

-- 3. RLS para Locations
alter table public.locations enable row level security;

create policy "Locations are viewable by everyone." 
on public.locations for select using ( true );

create policy "Users can create locations." 
on public.locations for insert with check ( auth.uid() = user_id );
