-- Habilitar extensión de vectores
create extension if not exists vector;

-- 1. TABLA: Perfiles de Usuario
create table public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  username text,
  avatar_url text,
  family_group_id uuid, -- Para compartir listas en el futuro
  updated_at timestamp with time zone
);

-- 2. TABLA: Categorías
create table public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  user_id uuid references public.profiles(id) not null,
  created_at timestamp with time zone default now()
);

-- 3. TABLA: Items de Inventario (Core)
create table public.inventory_items (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  name text not null,
  description text, -- Importante para la IA
  quantity integer default 1,
  unit text, -- 'pz', 'kg', 'L'
  category_id bigint references public.categories(id),
  expiry_date date,
  is_consumed boolean default false,
  image_url text,
  
  -- Embedding para búsqueda semántica (1536 dimensiones para text-embedding-ada-002)
  embedding vector(1536), 
  
  created_at timestamp with time zone default now()
);

-- 4. TABLA: Tareas Comunales (Social)
create table public.communal_tasks (
  id bigint generated by default as identity primary key,
  created_by uuid references public.profiles(id) not null,
  title text not null,
  status text check (status in ('pending', 'done')) default 'pending',
  is_public boolean default true,
  created_at timestamp with time zone default now()
);

-- 5. TABLA: Listas de Compras (Automatización)
create table public.shopping_lists (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  generated_for_date date,
  items jsonb, -- Guardamos los items sugeridos como JSON para simplicidad
  created_at timestamp with time zone default now()
);

-- 6. FUNCIÓN: Búsqueda Semántica
create or replace function match_inventory(
  query_embedding vector(1536),
  match_threshold float,
  match_count int
)
returns table (
  id bigint,
  name text,
  description text,
  similarity float
)
language plpgsql
as $$
begin
  return query
  select
    inventory_items.id,
    inventory_items.name,
    inventory_items.description,
    1 - (inventory_items.embedding <=> query_embedding) as similarity
  from inventory_items
  where 1 - (inventory_items.embedding <=> query_embedding) > match_threshold
  order by inventory_items.embedding <=> query_embedding
  limit match_count;
end;
$$;

-- RLS: Security Policies
alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.inventory_items enable row level security;
alter table public.communal_tasks enable row level security;
alter table public.shopping_lists enable row level security;

-- Policies (Basic examples for owner access)
create policy "Public profiles are viewable by everyone." on profiles for select using ( true );
create policy "Users can insert their own profile." on profiles for insert with check ( auth.uid() = id );
create policy "Users can update own profile." on profiles for update using ( auth.uid() = id );

create policy "Categories are viewable by everyone." on categories for select using ( true );
create policy "Users can create categories." on categories for insert with check ( auth.uid() = user_id );

create policy "Inventory items are viewable by everyone." on inventory_items for select using ( true );
create policy "Users can insert their own items." on inventory_items for insert with check ( auth.uid() = user_id );
create policy "Users can update their own items." on inventory_items for update using ( auth.uid() = user_id );

create policy "Tasks are viewable by everyone." on communal_tasks for select using ( true );
create policy "Users can insert tasks." on communal_tasks for insert with check ( auth.uid() = created_by );
create policy "Users can update tasks." on communal_tasks for update using ( true ); -- Simplified for demo

create policy "Shopping lists are viewable by owner." on shopping_lists for select using ( auth.uid() = user_id );
